development:
  bucket_name: development_documents
  access_key_id:    AKIAIVOIX7LX5XPE5V3A 
  secret_access_key:    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 

test:
  bucket_name: test_documents
  access_key_id:  AKIAIVOIX7LX5XPE5V3A
  secret_access_key: 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 

production:
  bucket_name: production_documents
  access_key_id: AKIAIVOIX7LX5XPE5V3A
  secret_access_key: 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
