#
# Development login at www.authorize.net:  flobridge_test, PayDay4u
#
development:
  login_id: 4BXF9Xx6qj
  transaction_key: 386884GTrV7Yz2j7

test:
  login_id: 4BXF9Xx6qj
  transaction_key: 386884GTrV7Yz2j7

production:
  login_id: 328xxsZUE
  transaction_key: 39228E89waxR2SRD
