development:
  bin_path: c:/sphinx/bin
  port: 3312
  searchd_binary_name: searchd
  indexer_binary_name: indexer

test:
  port: 3312
  bin_path: /usr/local/sphinx/bin
  searchd_binary_name: searchd
  indexer_binary_name: indexer

production:
  port: 3312
  bin_path: /usr/local/sphinx/bin
  searchd_binary_name: searchd
  indexer_binary_name: indexer