development:
  username: Flobridge
  password: Fl0Br1dg3
  api_key: c739a62735cbbcff97daa43c716822db5fb9d26a
  group_id: 29134
  shortcode: 91011

test:
  username: Flobridge
  password: Fl0Br1dg3
  api_key: c739a62735cbbcff97daa43c716822db5fb9d26a
  group_id: 29134
  shortcode: 91011

production:
  username: Flobridge
  password: Fl0Br1dg3
  api_key: c739a62735cbbcff97daa43c716822db5fb9d26a
  group_id: 29134
  shortcode: 91011
